Add ERA5-forced ACCESS-OM2 runs
ACCESS-NRI/access-nri-intake-catalog pull request #130
Opened 2023-10-17 02:10 UTC by dougiesquire

Adds the runs described in this ACCESS-Hive Forum post: https://forum.access-hive.org.au/t/era-5-forced-access-om2-simulations/1103

Closes #127

2023-10-17 10:19 UTC, dougiesquire commented
Some additional fields need to be added to the `metadata.yaml` files for these runs. I've created new versions of these files with the additional fields here: `/scratch/ik11/ds0092`. @rmholmes would you mind taking a look at these and copying them to the corresponding run directories if you're happy with them?

If you think it's worthwhile, it could be helpful to add some additional info to the descriptions fields to clarify:
- `1deg_jra55_iaf_era5comparison`: how is this different than the `1deg_jra55_iaf_omip2_cycle*` runs?
- `1deg_jra55v14_ryf`: how is this different than the `1deg_jra55_ryf9091_gadi` run? Just the JRA55 version?
- `025deg_jra55_iaf_era5comparison`: how is this different than the `025deg_jra55_iaf_omip2_cycle*` runs?
- `025deg_jra55_ryf_era5comparison`: how is this different than the `025deg_jra55_ryf9091_gadi` run? Just the JRA55 version?

2023-10-17 23:06 UTC, dougiesquire commented
@anton-seaice would you mind casting your eyes on this?

2023-10-19 22:10 UTC, anton-seaice requested changes

2023-10-19 22:10 UTC, anton-seaice commented on config/access-om2.yaml
I tried to run a test copy of 'build_all.sh' to output to scratch, and it gave the error the 'name' property is missing in the first added file. I didn't check the other files or for other missing properties.

I remember we talked about versioning, but would it be clearer if the metadata.yaml has the github version in it?

2023-10-19 22:18 UTC, dougiesquire commented on config/access-om2.yaml
> +  - metadata_yaml: /g/data/ik11/outputs/access-om2/1deg_jra55v14_ryf/metadata.yaml
Yeah, all of the `metadata.yaml` files in `/g/data/ik11/outputs` are missing a number of fields at the moment. I've created versions of the files with the necessary fields added here `/scratch/ik11/ds0092` and ask Ryan to check these before copying them across to the `/g/data/ik11/outputs`. See this comment: https://github.com/ACCESS-NRI/access-nri-intake-catalog/pull/130#issuecomment-1766117003

2023-10-19 22:19 UTC, dougiesquire commented on config/access-om2.yaml
> but would it be clearer if the metadata.yaml has the github version in it?

The github version of what?

2023-10-19 22:34 UTC, anton-seaice commented on config/access-om2.yaml
> +  - metadata_yaml: /g/data/ik11/outputs/access-om2/1deg_jra55v14_ryf/metadata.yaml
Oh ofcourse :)

2023-10-19 22:42 UTC, anton-seaice commented on config/access-om2.yaml
This line

`url: https://github.com/rmholmes/1deg_era5_iaf/tree/ryan_testing`

doesn't specify a unique version - just the repo, which could be changed after the run etc

2023-10-19 22:50 UTC, anton-seaice commented
I think this is not accurate for the ERA runs
```
1 degree ACCESS-OM2 global model configuration under '
                    'the RYF9091 Repeat\n'
                    'Year Forcing strategy outlined by Stewart et al. '
                    '(2020), \n'
                    'https://doi.org/10.1016/j.ocemod.2019.101557.
```

This document is about JRA55

2023-10-20 00:07 UTC, dougiesquire commented on config/access-om2.yaml
I see. Yeah, including the commit hash is definitely a good idea where it makes sense to do so. In many cases, the configuration changes throughout the model run, so there isn't one hash. My approach has been to leave this up to the person who ran the model

2023-10-20 02:02 UTC, dougiesquire commented
> I think this (from the description) is not accurate for the ERA runs
> 
> ```
> 1 degree ACCESS-OM2 global model configuration under '
>                     'the RYF9091 Repeat\n'
>                     'Year Forcing strategy outlined by Stewart et al. '
>                     '(2020), \n'
>                     'https://doi.org/10.1016/j.ocemod.2019.101557.
> ```
> 
> The document in the DOI is about JRA55

Hopefully @rmholmes can comment/improve

2023-10-31 01:26 UTC, rmholmes commented
Sorry for the slowness on this.

Thanks @dougiesquire for providing the updated meta data. I've added a few updates on top of yours and copied them to the appropriate directories in `ik11`. If you want to see what I changed, see the last two commits at https://github.com/rmholmes/era5_metas/commits/main. I think they should be all good now.

2023-10-31 23:32 UTC, dougiesquire commented
Great - thanks heaps @rmholmes!

2023-11-02 00:37 UTC, anton-seaice commented
Based on the updated metadata.yaml files for the 8 relevant runs being updated and moved in ik11, I managed to build datastores (using bin/build_all.sh) for new added model runs.

Log files attached

[v127_OM2_ERA5.tar.gz](https://github.com/ACCESS-NRI/access-nri-intake-catalog/files/13232869/v127_OM2_ERA5.tar.gz)
[conda_env.yaml.txt](https://github.com/ACCESS-NRI/access-nri-intake-catalog/files/13232880/conda_env.yaml.txt)
[build_all.sh_as.o99597320.txt](https://github.com/ACCESS-NRI/access-nri-intake-catalog/files/13232881/build_all.sh_as.o99597320.txt)

2023-11-02 00:38 UTC, anton-seaice approved these changes

2023-11-02 02:40 UTC, merged